"""Spectrum: Adaptive Spectral Feature Forecasting for ComfyUI.

Drop-in KSampler replacement that accelerates diffusion sampling via
Chebyshev polynomial feature forecasting (Han et al., CVPR 2026).

On "actual" steps the full model runs and block outputs are captured.
On "cached" steps all transformer blocks are skipped — only t_embedder +
final_layer + unpatchify execute, using predicted features from a
Chebyshev ridge-regression fit. Works with any ComfyUI sampler (Euler,
DPM, er_sde, etc.) because caching is handled transparently inside the
model_function_wrapper.

Node tiers:
  - SpectrumKSampler: unified drop-in — acceleration + SEA scheduling
    (refresh_ratio dial; -1 = off) + modulation guidance (mod_w_profile;
    'off' = none). Subsumes the former basic / ModGuidance / SEA samplers,
    whose class keys remain as hidden deprecated aliases.
  - SpectrumKSamplerAdvanced: + full Spectrum tuning, raw mod-guidance scalars,
    adapter selection, and DCW
  - SpectrumSPDKSampler (SPEED): + SPD multi-resolution prefix (low-res early,
    spectral-expand to full res at the handoff, Spectrum-forecasted tail)
  - SpectrumSPDLoRAKSampler: SPEED with the resolution schedule auto-read from
    an SPD-trained LoRA's metadata
  - AnimaModGuidance: standalone mod-guidance model patcher (composes with any sampler)
  - DiTSpectrumPatch: standalone Spectrum MODEL patcher (no sampling)

Also registers an `er_sde_cns` entry in the global sampler dropdown: Colored
Noise Sampling (Davidson et al., arXiv 2605.30332) — the ER-SDE solver with
per-step noise recolored toward unresolved frequency bands. Pick it in any
KSampler's `sampler_name` field; composes with the Spectrum / mod-guidance
patches above. Anima-calibrated γ; auto-downloaded on first use.
"""

# ── anima_lora resolution ──────────────────────────────────────────────────
# The node's pure-compute kernels (FSG / SMC / CNS / DCW / SPD numerics) live in
# anima_lora and are imported as ``library.*`` / ``networks.*``. Two install
# shapes are supported, exactly like the other Anima ComfyUI nodes:
#   1. Inside the anima_lora repo (dev): ``parents[1]`` of this file is the repo
#      root, so the live ``library/`` / ``networks/`` are reachable — edits there
#      are picked up automatically.
#   2. Standalone ComfyUI install: fall back to the bundled subset under
#      ``_vendor/`` (generated by ``scripts/release/sync_vendor.py``).
# Live wins when present (inserted at sys.path front); vendor is appended as the
# fallback. Must run BEFORE importing the node modules below, which import
# ``library.*`` / ``networks.*`` at load time.
import sys as _sys
from pathlib import Path as _Path

_HERE = _Path(__file__).resolve().parent
_ANIMA_LORA = _HERE.parents[1]
_VENDOR = _HERE / "_vendor"
if (_ANIMA_LORA / "library").is_dir() and str(_ANIMA_LORA) not in _sys.path:
    _sys.path.insert(0, str(_ANIMA_LORA))
if _VENDOR.is_dir() and str(_VENDOR) not in _sys.path:
    _sys.path.append(str(_VENDOR))

from .cns import register_cns_sampler
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

register_cns_sampler()

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
